// vue-element-admin/src/views/good/good-form.vue
<template>
  <div class='good-form' style="width:500px;">
    <el-form :model="ruleForm" :rules="rules" ref="ruleForm" label-width="100px" class="demo-ruleForm">

      <el-form-item label="商品名称" prop="name">
        <el-input v-model="ruleForm.name"></el-input>
      </el-form-item>

      <el-form-item label="商品图片" prop="img">
        <ImgUpload v-model='ruleForm.img' />
      </el-form-item>

      <el-form-item label="商品描述" prop="desc">
        <el-input type="textarea" v-model="ruleForm.desc"></el-input>
      </el-form-item>

      <el-form-item label="商品品类" prop="cate">
        <!-- <CateSelect :value='ruleForm.cate' @input='ruleForm.cate=$event' /> -->

        <CateSelect v-model='ruleForm.cate' />
      </el-form-item>

      <el-form-item label="商品价格" prop="price">
        <el-input-number v-model="ruleForm.price" controls-position="right" :min="0"></el-input-number>
      </el-form-item>



      <el-form-item label="商品排名" prop="rank">
        <el-input-number v-model="ruleForm.rank" controls-position="right"  :min="0"></el-input-number>
      </el-form-item>

      <el-form-item label="是否热销" prop="hot">
        <el-switch v-model="ruleForm.hot"></el-switch>
      </el-form-item>

      <el-form-item>
        <el-button type="primary" @click="submit('ruleForm')">提交</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script>

import CateSelect from './components/CateSelect'
import ImgUpload from './components/ImgUpload'
import { fetchGoodForm, fetchGoodInfo } from '@/api/good'

export default {
  name: 'GoodForm',
  components: { CateSelect, ImgUpload },
  props: {
    id: { type: String, default: '' }
  },
  data () {

    var validatePrice = (rule, value, callback) => {
      if (value <= 0) {
        callback(new Error('价格不能小于零'));
      } else {
        callback()
      }
    }

    return {
      ruleForm: {
          name: '',
          img: '',
          hot: false,
          desc: '',
          price: 0,
          cate: '',
          rank: 0
        },
        rules: {
          // 编写验证规则：要验证什么，如果违背规则给什么提示，触发机制
          name: [
            { required: true, message: '商品名称是必须字段', trigger: 'blur' },
            { pattern: /[\u4e00-\u9fa5]{4,6}/, message: '长度在 4 到 6 个字符', trigger: 'blur' }
          ],
          img: [
            { required: true, message: '商品图片是必须字段', trigger: 'blur' },
          ],
          desc: [
            { pattern: /[\u4e00-\u9fa5]{20,24}/, message: '长度在 20到 24个字符', trigger: 'blur' }
          ],
          price: [
            { validator: validatePrice, trigger: 'blur' }
          ]
        }
    }
  },
  mounted () {
    console.log('---id', this.id)
    if (this.id) {
      fetchGoodInfo(this.id).then(res=>{
        console.log('商品详情', res)
        this.ruleForm = res.data.info
      })
    }
  },
  methods: {
    submit (form) {
      console.log('---form', form)
      const data = { ...this.ruleForm }
      if (this.id) data['id'] = this.id
      console.log('---data', data)
      // return false
      fetchGoodForm(data).then(res=>{
        this.$message({
          type: 'success',
          message: `${this.id?"修改成功":"添加成功"}`,
          duration: 1500,
          onClose: () => {
            console.log('msg消失')
            this.$router.replace('/good/list')
          }
        })
      })
    }
  }
}
</script>

<style lang="scss" scoped>
.good-form {
  box-sizing: border-box;
  margin: 25px;
}
</style>

// react-project/src/views/good/GoodForm.js

import React, { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux'
import { useNavigate, useParams } from 'react-router-dom'

import {
  AutoComplete,
  Button,
  Cascader,
  Checkbox,
  Col,
  Form,
  Input,
  InputNumber,
  Row,
  Select,
  Switch,
  message
} from 'antd';

import CateSelect from './components/CateSelect'
import SingleUpload from './components/SingleUpload'
import './style.scss'

import { goodSubmit, goodDone, goodInfo } from '@/store/actions'

const { Option } = Select;

export default () => {

  const [form] = Form.useForm()
  const navigate = useNavigate()
  const { id } = useParams()
  const dispatch = useDispatch()
  const { done, info } = useSelector(state=>state.good)

  console.log('---id', id)

  useEffect(()=>{
    // 当有id时，表示是编辑，获取商品详情
    if (id) {
      dispatch(goodInfo(id))
    }
  }, [])

  useEffect(()=>{
    if (info._id) {
      // 使用异步数据填充表单初始值
      form.setFieldsValue(info)
    }
  }, [info])

  useEffect(()=>{
    if (done===1) {
      message.success(`${id?'修改成功':'添加成功'}`, 1, ()=>navigate(-1))
    }
    return () => {
      // 清缓存（重置good子store）
      dispatch(goodDone(0))
    }
  }, [done])

  const onFinish = values => {
    let data = {...values}
    if (id) {
      data.id = id
    }
    dispatch(goodSubmit(data))
  }

  return (
    <div className='goodform'>
      <div className='wrap'>
        <Form
          labelCol={{ span: 4}}
          wrapperCol={{ span: 10 }}
          onFinish={onFinish}
          form={form}
          initialValues={{
            img: '',
          }}
          scrollToFirstError
          validateTrigger={['onChange','onBlur']}
        >
          <Form.Item
            name='name'
            label='商品名称'
            validateTrigger='onBlur'
            rules={[
              { required: true, message: '商品名称是必填信息' },
              { pattern: /[\u4e00-\u9fa5]{4,8}/, message:'商品名称只支持4~8个中文汉字' }
            ]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            name='desc'
            label='商品描述'
            validateTrigger='onBlur'
            rules={[
              { required: true, message: '商品描述是必填信息!' },
              { min: 20, max: 30, message: '商品描述在20~30个字之间' }
            ]}
            hasFeedback
          >
            <Input.TextArea />
          </Form.Item>

          <Form.Item
            name="cate"
            label="商品品类"
            dependencies={['password']}
            hasFeedback
            rules={[
              { required: true, message: '请选择商品品类' }
            ]}
          >
            <CateSelect showAll={false} allowClear={false} />
          </Form.Item>

          <Form.Item
            name="price"
            label="商品价格"
            tooltip="What do you want others to call you?"
            validateTrigger='onBlur'
            rules={[
              { required: true, message: '请输入商品价格' },
              {
                validator: (_, value) => {
                  if (value > 1) {
                    return Promise.resolve()
                  } else {
                    return Promise.reject(new Error('商品价格不能小于1元'))
                  }
                }
              }
            ]}
          >
            <InputNumber />
          </Form.Item>

          <Form.Item
            name="img"
            label="商品图片"
            rules={[
              { required: true, message: '商品图片是必填字段' },
            ]}
          >
            <SingleUpload />
          </Form.Item>

          <Form.Item
            label='是否热销'
            name="hot"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>

          <Form.Item wrapperCol={{offset:4}}>
            <Button type="primary" htmlType="submit">
              { id ? '修改' : '添加' }
            </Button>
          </Form.Item>
        </Form>
      </div>
    </div>
  )
}
